# Generated by Django 4.0.2 on 2022-02-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facultytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=200, null=True)),
                ('fmiddlename', models.CharField(blank=True, max_length=200, null=True)),
                ('flastname', models.CharField(blank=True, max_length=200, null=True)),
                ('fnumber', models.CharField(blank=True, max_length=200, null=True)),
                ('gsis', models.IntegerField(blank=True, null=True)),
                ('gpn', models.IntegerField(blank=True, null=True)),
                ('philhealth', models.IntegerField(blank=True, null=True)),
                ('tin', models.IntegerField(blank=True, null=True)),
                ('pagibig', models.IntegerField(blank=True, null=True)),
                ('others', models.CharField(blank=True, max_length=200, null=True)),
                ('fcperson', models.CharField(blank=True, max_length=200, null=True)),
                ('fcnumber', models.IntegerField(blank=True, null=True)),
                ('faddress', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='studenttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('middlename', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('course', models.CharField(choices=[('COET', 'Computer Engineering Technology'), ('BSIE', 'BS Industrial Education')], max_length=200)),
                ('snumber', models.CharField(blank=True, max_length=200, null=True)),
                ('cperson', models.CharField(blank=True, max_length=200, null=True)),
                ('cnumber', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('idpic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
