# Generated by Django 4.0.3 on 2022-05-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idrequestApp', '0002_remove_studenttable_date_alter_studenttable_idpic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttable',
            name='idpic',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
    ]
