# Generated by Django 4.0.3 on 2022-05-27 03:32

from django.db import migrations, models
import idrequestApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('idrequestApp', '0004_alter_studenttable_idpic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttable',
            name='idpic',
            field=models.ImageField(blank=True, null=True, upload_to=idrequestApp.models.filepath),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=idrequestApp.models.filepath),
        ),
    ]
