# Generated by Django 4.0.3 on 2022-03-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idrequestApp', '0005_admin_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
        migrations.AddField(
            model_name='registration',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
