# Generated by Django 4.0.2 on 2022-02-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idrequestApp', '0003_facultytable_status_studenttable_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultytable',
            name='idpic',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
        migrations.AddField(
            model_name='facultytable',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='img/&y '),
        ),
    ]
